# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
# org.gradle.java.home=C:/Program Files/Java/jdk-21
# Fabric Properties
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.19.2
# Mod Properties
mod_version=1.0.0
maven_group=su.energyclient
archives_base_name=energy
# Dependencies
fabric_version=0.141.3+1.21.11
